language: php
sudo: required
services:
- docker
php:
- '7.1'
script:
- sh generate-client.sh
env:
  global:
    secure: 1IANbnlF9LqOk5mVUpq/3pT7ZhH9HtlsaaXgE84oywCeYNGtoqIDlhxZ7MJqKKFfAMJyE6D9IGaY2xmnSn/xXqKOwc42KY51eBo623xeHXOfgZ1be+ZqC47jCKal4kILYlRTcxQPJA+kJNiQzCs52jtZY9NIRmKNBzFC4k8bk2QfkrKIDTMmJISo1j1r9hBLpPJpWQVjA9dbOlOfFc4mYntdISZKTxWHukEHP1Fz+fUMW+D0D4Z6SnBHawnvWKGDnTNyZD9K/1OfcT6O/adTov6DTuNy728T/9ANd9tU8l+S/aCNrg3rOEFbbBcuTZPZ72qWzp7Y8q1eLUc+YKUSchwBH+ybg/1hyRkt7o8Ig4U/+ZeMelKVllOODEcUTD/EkkwxQJXjtMW0eJZ+9ByRptbsUXAgotevIT6POmLYqJUadv2u9/uTzFrKvLiMK8kuW9fbZZLMFPG2tPlNIGhInzJiI2e1fD2ctWV3+oUYw3/iO+g1DiHMzxRkJKcPj8jK5Zr/fGXG7KwBgQPk6TWY51Ra/LK/cxj0rlxo+NpRacD9iI6lhMUHcx6LaLRx5X1lWH6w48z8hn72qv5vDyW/hkGeNaKdT23/X1c5L37zcvZ3LsIuXa23oa8Unh86NGSmWfDhciyj3lMYMV92CzhB+0UDGGkeFA2WJnRsosmeAT4=
