version: '2'
services:
  wordpress:
    build: .
    image: wp-unit-test-api/plugin
    restart: always
    depends_on:
      - db
    links:
    - db:mysql
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html/wp-content/plugins/wp-unit-test-api
    environment:
      WORDPRESS_DB_PASSWORD: password
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
